# Generated by Django 3.1.2 on 2020-11-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighbourhood',
            field=models.CharField(blank=True, default='kitengela', max_length=25),
        ),
    ]
